global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Job 1 : Métriques du serveur (Node Exporter)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Job 2 : Métriques du cluster Kafka
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Job 3 : Métriques des conteneurs Docker (Telegraf)
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']

  # Job 4 : Métriques du cluster MongoDB Sharded
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']